---
title: "Initial Project Info"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(primer.data)
library(tidyverse)
library(ggplot2)
```

```{r}
coup_data <- read_csv(file = "/Users/Nansi/Desktop/Gov_1005/Final_Project/Coup_Data_v2.0.0.csv")
glimpse(coup_data)

top_10_coups <- coup_data %>% 
  group_by(country) %>% 
  filter(event_type == "coup") %>% 
  select(country, event_type, realized) %>% 
  summarise(total_coup = sum(realized)) %>% 
  arrange(desc(total_coup)) %>% 
  slice(1:10) 

top_10_coups %>% 
  ggplot(aes(x = fct_reorder(country, total_coup),
             y = total_coup)) +
  labs(title = "Top 10 Countries with the Most Successful Coups from 1945- 2019",
       subtitle = "South and Central American countries have had the most successful coups",
       caption = "Source: Cline Center Coup DՎtat Project Dataset",
       x = "Country",
       y = "Number of Successful Coups") +
  coord_flip() +
  theme_minimal() +
  geom_col(fill = "darkolivegreen4")
  
```
```{r}


attempted_coups <-coup_data %>% 
                    group_by(country) %>% 
                    filter(attempt == 1) %>% 
                    select(country, attempt) %>% 
                    summarise(failed_attempts = sum(attempt)) %>% 
                    arrange(desc(failed_attempts)) %>% 
                    slice(1:10) 

attempted_coups %>% 
  ggplot(aes(x = fct_reorder(country, failed_attempts),
             y = failed_attempts)) +
  labs(title = "Top 10 Countries with the Most Unsuccessful Coups from 1945- 2019",
       subtitle = "Coups fail all over the world",
       caption = "Source: Cline Center Coup DՎtat Project Dataset",
       x = "Country",
       y = "Number of Unsuccessful Coups") +
  coord_flip() +
  theme_minimal() +
  geom_col(fill = "darkolivegreen4")
```

