---
title: "model data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(rstanarm)
library(tidybayes)
library(gtsummary)
library(Rcpp)
library(gt)
library(patchwork)
```

```{r intial data}

coup_data <- read_csv(file = "Coup_Data/Coup_Data_v2.0.0.csv")




model_data <- coup_data %>% 
                  select( - c(unrealized, conspiracy, attempt, coup_id, day, noharm)) %>%
                  group_by(year) %>% 
                  arrange(desc(year)) %>% 
                  # making  a new variable for Middle east since it's the region
                  # I'm interested in exploring, this will allow
                  # me to create interaction terms that better predict the
                  # causal effect of different coup types.
                  mutate(mena = if_else(country %in% c("Algeria"," Bahrain", 
                                                         "Djibouti", "Egypt", 
                                                         "Iran", "Iraq", "Israel", 
                                                         "Jordan", "Kuwait", "Lebanon",
                                                         "Libya", "Malta", "Morocco",
                                                         "Oman", "Qatar", "Saudi Arabia", 
                                                         "Syria", "Tunisia", "United Arab Emirates",
                                                         "Yemen"), TRUE, FALSE))
saveRDS(model_data, file = "Model_Data")
```

```{r fit_1}

#I have selected these variables because they represent the top 4 most common
#coup types as well as other factors that may be significant to the success of a
#coup (loss of life). As I would like to concentrate on the implications of
#these effects in the Middle East, I have created a dummy variable specific to
#the Middle East and seek to explore its interaction with the coup types to
#determine if they have as significant causal effect.

fit_1 <- stan_glm(realized ~ popular + military + foreign + palace + killed + mena - 1 + mena*popular + mena*military +  mena*foreign + mena*palace,
                  #add interaction terms? -> military, middle east, event_type, military*middle east?
                  family = "binomial",
                  model_data,
                  refresh = 0,
                  seed = 13)


saveRDS(fit_1, file = "fit_1")


#Middle_east* interaction with other variables- interaction between two terms that matter - one model that captures the complete reality 

#impossible to understand the intercept for a binomial, but you can show that event_type is significant -> create posterior plot -> explore with different newobs 

#changing new obs to explore data
```




```{r warning=FALSE}
Table_1 <- tbl_regression(fit_1, 
                           intercept = TRUE, 
                           estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
            as_gt()
              # Using Beta as the name of the parameter column is weird.
              
Table_1



```


$realized_{i} =  \beta_1 popular_{i} + \beta_2 dissident_{i} +  \beta_3 foreign_{i} + \beta_4 military + \beta_5 rebel + \beta_6 palace_{i} + \beta_7 auto + \epsilon_{i}$ 

```{r,  warning=FALSE}


popular <- unique(model_data$popular)
military <- unique(model_data$military)
foreign <- unique(model_data$foreign)
palace <- unique(model_data$palace)
killed <- unique(model_data$killed)
mena <- unique(model_data$mena)

newobs_1 <- expand_grid( killed, popular, military, foreign, palace, mena) 

pe_1 <- add_fitted_draws(newobs_1, fit_1) 


palace_pe <- pe_1 %>% 
              ggplot(aes(x = .value, y = as.character(palace == 1), fill = mena)) +
              stat_slab(alpha =.5) +
              labs(x = "Probability of Realization",
                   y = "Palace Coup",
                   fill = "MENA") +
              theme(legend.title = element_text(face = "bold")) +
              theme_tidybayes() 
palace_pe

```

```{r pe_2}

popular_pe <- pe_1 %>% 
                ggplot(aes(x = .value, y = as.character(popular == 1), fill = mena)) +
                stat_slab(alpha =.5) +
                labs(x = "Probability of Realization",
                     y = "Popular Coup",
                     fill = "MENA") +
                theme(legend.title = element_text(face = "bold")) +
                theme_tidybayes()
 
```

```{r}
foreign_pe <- pe_1 %>% 
                ggplot(aes(x = .value, y = as.character(foreign == 1), fill = mena)) +
                stat_slab(alpha =.5) +
                labs(x = "Probability of Realization",
                     y = "Foreign Backed Coup",
                     fill = "MENA") +
                theme(legend.title = element_text(face = "bold")) +
                theme_tidybayes()
```

```{r}
military_pe <- pe_1 %>% 
                ggplot(aes(x = .value, y = as.character(military), fill = mena)) +
                labs(x = "Probability of Realization",
                     y = "Military Coup",
                     fill = "MENA") +
                theme(legend.title = element_text(face = "bold")) +
                stat_slab(alpha =.5) +
                theme_tidybayes()
```

```{r model_visual}

mena_interaction <- palace_pe + popular_pe + foreign_pe + military_pe

mena_interaction +
   plot_annotation(title = "Posterior Distribution",
                   subtitle = "Based on a 2020 field experiment encouraging
                   voting by mail, more specifically the `Neighborhood` treatment",
                   caption = "Source: Hopkins et al (2021)") 

```

