---
title: "map_testing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(highcharter)
library(dplyr)
library(maps)
library(tidyverse)
library(ggplot2)
library(janitor)

```

```{r}
coup_data <- read_csv(file = "Coup_Data/Coup_Data_v2.0.0.csv")

Clean_coup <- coup_data %>% 
  select( - c( unrealized, conspiracy, attempt, coup_id)) %>% 
  group_by(year) %>% 
  arrange(desc(year))

map_info <- Clean_coup %>% 
              group_by(country) %>% 
              select(country, event_type, realized) %>% 
              filter(event_type == "coup") %>% 
              rename(mapname = "country")  %>% 
              
              group_by(event_type, mapname) %>%
               summarise(n = n(),
                        .groups = "drop") %>% 
              inner_join(iso3166,
                         by = "mapname") %>% 
              rename("iso-a3" = a3)



total <-  Clean_coup %>% 
              group_by(country) %>% 
              select(country, event_type, realized) %>% 
              rename(mapname = "country") %>% 
              group_by(mapname, event_type) %>% 
              summarise(n = n(),
                        .groups = "drop") 
              
```

```{r}




map_1 <- hcmap(
  map = "custom/world-highres3", # high resolution world map
  data = map_info, # name of dataset
  joinBy = c("iso-a3"),
  name = "coups",
  value = "n",
  showInLegend = TRUE, # hide legend
  nullColor = "#DADADA",
  download_map_data = TRUE,
  dataLabels = list(enabled = TRUE, format = "{point.country}",
  tooltip = list(
    valueDecimals = 2)))%>% 
  hc_mapNavigation(enabled = FALSE) %>%
  hc_legend("none") %>%
  hc_title(text = "Coup Map from 1949 - 2019") # title


          


```

