---
title: "model data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(rstanarm)
library(tidybayes)
library(gtsummary)
library(Rcpp)
library(gt)
library(ggdist)
library(patchwork)
```


```{r}
x <- read_csv(file = "../Coup_Data/Coup_Data_v2.0.0.csv")
```






```{r intial data}

coup_data <- read_csv(file = "../Coup_Data/Coup_Data_v2.0.0.csv", col_types = cols(
  .default = col_double(),
  coup_id = col_character(),
  country = col_character(),
  month = col_character(),
  day = col_character(),
  event_type = col_character()
))




model_data <- coup_data %>% 
                  select( - c(unrealized, conspiracy, attempt, coup_id, day, noharm)) %>%
                  group_by(year) %>% 
                  arrange(desc(year)) %>% 
                  # making  a new variable for Middle east since it's the region
                  # I'm interested in exploring, this will allow
                  # me to create interaction terms that better predict the
                  # causal effect of different coup types.
                  mutate(mena = if_else(country %in% c("Algeria"," Bahrain", 
                                                         "Djibouti", "Egypt", 
                                                         "Iran", "Iraq", "Israel", 
                                                         "Jordan", "Kuwait", "Lebanon",
                                                         "Libya", "Malta", "Morocco",
                                                         "Oman", "Qatar", "Saudi Arabia", 
                                                         "Syria", "Tunisia", "United Arab Emirates",
                                                         "Yemen"), TRUE, FALSE))
#saveRDS(model_data, file = "Model_Data.rds")
```

```{r fit_1}

#I have selected these variables because they represent the top 4 most common
#coup types as well as other factors that may be significant to the success of a
#coup (loss of life). As I would like to concentrate on the implications of
#these effects in the Middle East, I have created a dummy variable specific to
#the Middle East and seek to explore its interaction with the coup types to
#determine if they have as significant causal effect.

fit_1 <- stan_glm(realized ~ popular + military + foreign + palace + mena + mena*popular + mena*military +  mena*foreign + mena*palace,
                  #add interaction terms? -> military, middle east, event_type, military*middle east?
                  family = "binomial",
                  model_data,
                  refresh = 0,
                  seed = 13)


saveRDS(fit_1, file = "fit_1.rds")


#Middle_east* interaction with other variables- interaction between two terms that matter - one model that captures the complete reality 

#impossible to understand the intercept for a binomial, but you can show that event_type is significant -> create posterior plot -> explore with different newobs 

#changing new obs to explore data
```




```{r warning=FALSE}
Table_1 <- tbl_regression(fit_1, 
                           intercept = TRUE,  exponentiate = TRUE,
                           estimate_fun = function(x) style_sigfig(x, digits = 4)) %>%
            as_gt()
              # Using Beta as the name of the parameter column is weird.
              

Table_1

gtsave(Table_1,"Table_1.png")

# being in the Middle East doesn't matter

```


$realized_{i} =  \beta_1 popular_{i} + \beta_2 military_{i} +  \beta_3 foreign_{i} + \beta_4 palace_{i} + \beta_5 menaTRUE_{i} + \beta_6 popular*menaTRUE_{i} + \beta_7 military*menaTRUE_{i}  + \beta_8 foreign*menaTRUE_{i} +  \beta_9 palace*menaTRUE_{i} + \epsilon_{i}$ 
#import knitted r markdown (google how)

```{r,  warning=FALSE}
popular <- unique(model_data$popular)
military <- unique(model_data$military)
foreign <- unique(model_data$foreign)
palace <- unique(model_data$palace)
mena <- unique(model_data$mena)

newobs_1 <- expand_grid(popular, military, foreign, palace, mena) 

pe_1 <- add_fitted_draws(newobs_1, fit_1) %>% 
      as_tibble() %>% 
      mutate(pop_for = paste(popular, foreign, sep = "-"))

#saveRDS(pe_1, "pe_1.rds")


coup_plot <- pe_1 %>% 
              filter(military == 0,
                     palace == 0) %>% 
              ggplot(aes(x = .value, y = as.character(pop_for), fill = mena)) +
              stat_slab(alpha =.5) +
              labs(title = "Posterior Probability Distributions of Palace and Foreign Backed Coups",
                   subtitle = "The probability of a coup succeeding increases with popular resistance",
                   x = "Probability of Success",
                   y = "Popular and Foriegn Backed Coup Combinations",
                   fill = "MENA") +
              theme(legend.title = element_text(face = "bold")) +
              scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
              theme_tidybayes() 

coup_plot
```

```{r pe_2}

popular_pe <- pe_1 %>% 
                filter(palace == 0,
                     popular %in% 1,
                     military == 0,
                     foreign == 0) %>% 
                ggplot(aes(x = .value, y = as.character(popular == 1), fill = mena)) +
                stat_slab(alpha =.5) +
                labs(x = "Probability of Realization",
                     y = "Popular Coup",
                     fill = "MENA") +
                scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
                theme(legend.title = element_text(face = "bold")) +
                theme_tidybayes()

popular_pe
 
```

```{r}
foreign_pe <- pe_1 %>% 
                filter(palace == 0,
                       popular == 0,
                       military == 0,
                       foreign == 1) %>% 
                ggplot(aes(x = .value, y = as.character(foreign == 1), fill = mena)) +
                stat_slab(alpha =.5) +
                labs(x = "Probability of Realization",
                     y = "Foreign Backed Coup",
                     fill = "MENA") +
                theme(legend.title = element_text(face = "bold")) +
                scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
                theme_tidybayes()

foreign_pe
```

```{r}
military_pe <- pe_1 %>% filter(palace == 0,
                               popular == 0,
                               military == 1,
                               foreign == 0) %>% 
                ggplot(aes(x = .value, y = as.character(military == 1), fill = mena)) +
                labs(x = "Probability of Realization",
                     y = "Military Coup",
                     fill = "MENA") +
                theme(legend.title = element_text(face = "bold")) +
                stat_slab(alpha =.5) +
                scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
                theme_tidybayes()

military_pe
```

```{r model_visual}

mena_interaction <- palace_pe + popular_pe + foreign_pe + military_pe


mena_plots <- mena_interaction +
   plot_annotation(title = "Posterior Probability Distribution for Top 4 Coup Types in MENA",
                   subtitle = "For the most part they are more popular outside of the MENA",
                   caption = "Source: Hopkins et al (2021)") &
    coord_cartesian(xlim = c(0,1.0)) 



```


```{r}

#newobs <- tibble(  = rep(c("Male", "Female"), 3), election_age = rep(c(30, 45, 60), 2),
                  #names = paste(sex, election_age, sep = "_"))

pe_1.2 <- posterior_epred(fit_1,
                          newdata = newobs_1) %>% 
                      as_tibble() %>% 
   
   #use set names to take heading names from newobs
                      set_names( newobs_1$names)
```

